# Generated by Django 2.1.7 on 2019-03-10 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_image', models.CharField(max_length=100, null=True)),
                ('datafile', models.FileField(null=True, upload_to='')),
                ('image_url', models.URLField(null=True)),
                ('text', models.TextField(help_text='Enter a caption', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
